
CREATE TABLE public.courses (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	category varchar(255) NULL,
	"name" varchar(255) NULL,
	teacher varchar(255) NULL,
	CONSTRAINT courses_pkey PRIMARY KEY (id)
);

CREATE TABLE public.students (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	age int4 NULL,
	last_name varchar(255) NULL,
	"name" varchar(255) NULL,
	course_id int8 NULL,
	CONSTRAINT students_pkey PRIMARY KEY (id),
	CONSTRAINT fk6jiqckumc6tm0h9otqbtqhgnr FOREIGN KEY (course_id) REFERENCES public.courses(id)
);

INSERT INTO courses (name, category, teacher) VALUES ('Matematicas', 'Ciencias exactas', 'Juan Diego Ossa');
INSERT INTO courses (name, category, teacher) VALUES ('Biologia', 'Ciencias', 'Leandro Jarammillo');
INSERT INTO courses (name, category, teacher) VALUES ('Programacion', 'Tecnologia', 'Neiro Figueroa');

INSERT INTO students (name, last_name, age, course_id) VALUES ('John', 'Serna', '26', 1);
INSERT INTO students (name, last_name, age, course_id) VALUES ('Andrea', 'Calle', '21', 2);
INSERT INTO students (name, last_name, age, course_id) VALUES ('Anyi', 'Hoyos', '22', 1);
INSERT INTO students (name, last_name, age, course_id) VALUES ('Santiago', 'Perez', '24', 3);